import { Mic, Radio, Send, Sparkles } from 'lucide-react';
import { useRef, useState } from 'react';
import type React from 'react';
import { api } from '../../services/api';
import type { ActivationStatus, CommandResponse } from '../../types/api';
export function CommandBar({ onResult, setActivation, onTaskCreated }: { onResult: (r: CommandResponse | string) => void; setActivation: React.Dispatch<React.SetStateAction<ActivationStatus>>; onTaskCreated: () => Promise<void> }) {
  const [command, setCommand] = useState(''); const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]);
  const route = async (text: string, source: 'text_command' | 'voice_command' = 'text_command') => { if (!text.trim()) return; setActivation((current) => ({ ...current, state: 'thinking', current_state: 'thinking' })); const res = await api.routeCommand(text, false, source); onResult(res); if (res.task) await onTaskCreated(); setActivation((current) => ({ ...current, state: res.activation_state === 'blocked' ? 'blocked' : res.requires_confirmation ? 'confirmation_required' : 'responding', current_state: res.activation_state === 'blocked' ? 'blocked' : res.requires_confirmation ? 'confirmation_required' : 'responding' })); window.setTimeout(() => setActivation((current) => ({ ...current, state: 'idle', current_state: 'idle' })), res.activation_state === 'blocked' ? 1800 : 2200); setCommand(''); };
  const send = async () => route(command);
  const handleTranscript = async (blob?: Blob) => { setActivation((current) => ({ ...current, state: 'transcribing', current_state: 'transcribing' })); const t = await api.transcribe(blob); const transcript = t.transcript.replace('Mock transcription: ', ''); onResult(t.message ?? `${t.transcript}${t.mocked ? ' (mock transcription)' : ''}`); setCommand(transcript); await route(transcript, 'voice_command'); };
  const pushToTalk = async () => { try { if (!recording && navigator.mediaDevices) { setActivation((current) => ({ ...current, state: 'listening', current_state: 'listening' })); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const r = new MediaRecorder(stream); recorder.current = r; r.ondataavailable = e => chunks.current.push(e.data); r.onstop = async () => { stream.getTracks().forEach(t=>t.stop()); await handleTranscript(new Blob(chunks.current, { type: 'audio/webm' })); }; r.start(); setRecording(true); } else { recorder.current?.stop(); setRecording(false); } } catch { setRecording(false); await handleTranscript(); } };
  const toggleWake = async () => setActivation(await api.toggleWake(true));
  return <div className="command-wrap"><div className="command-bar"><Sparkles className="spark" size={21}/><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{ if(e.key==='Enter') send(); }} placeholder="Type a command or ask anything..."/><button className={recording?'recording':''} onClick={pushToTalk} title="Push to talk"><Mic size={20}/></button><button onClick={toggleWake} title="Wake listening"><Radio size={20}/></button><button className="send" onClick={send}><Send size={20}/></button></div><p>Press <b>/</b> to see commands · Press <b>Ctrl + K</b> to quick search</p></div>;
}
