import { Mic, Radio, Send, Sparkles } from 'lucide-react';
import { useRef, useState } from 'react';
import { api } from '../../services/api';
import type { ActivationStatus, CommandResponse } from '../../types/api';
export function CommandBar({ onResult, setActivation }: { onResult: (r: CommandResponse | string) => void; setActivation: (a: ActivationStatus) => void }) {
  const [command, setCommand] = useState(''); const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]);
  const send = async () => { if (!command.trim()) return; const res = await api.routeCommand(command); onResult(res); setCommand(''); };
  const pushToTalk = async () => { try { if (!recording && navigator.mediaDevices) { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const r = new MediaRecorder(stream); recorder.current = r; r.ondataavailable = e => chunks.current.push(e.data); r.onstop = async () => { stream.getTracks().forEach(t=>t.stop()); const blob = new Blob(chunks.current, { type: 'audio/webm' }); const t = await api.transcribe(blob); onResult(`${t.transcript}${t.mocked ? ' (mock transcription)' : ''}`); setCommand(t.transcript.replace('Mock transcription: ', '')); }; r.start(); setRecording(true); } else { recorder.current?.stop(); setRecording(false); } } catch { const t = await api.transcribe(); onResult(`${t.transcript} (mock transcription; microphone unavailable)`); setCommand(t.transcript.replace('Mock transcription: ', '')); setRecording(false); } };
  const toggleWake = async () => setActivation(await api.toggleWake(true));
  return <div className="command-wrap"><div className="command-bar"><Sparkles className="spark" size={21}/><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{ if(e.key==='Enter') send(); }} placeholder="Type a command or ask anything..."/><button className={recording?'recording':''} onClick={pushToTalk} title="Push to talk"><Mic size={20}/></button><button onClick={toggleWake} title="Wake listening"><Radio size={20}/></button><button className="send" onClick={send}><Send size={20}/></button></div><p>Press <b>/</b> to see commands · Press <b>Ctrl + K</b> to quick search</p></div>;
}
