Write-Host "Lunex Windows-first development startup"
Write-Host ""
Write-Host "Terminal 1:"
Write-Host "cd backend"
Write-Host "python -m venv .venv"
Write-Host ".\.venv\Scripts\Activate.ps1"
Write-Host "pip install -r requirements.txt"
Write-Host "uvicorn app.main:app --reload --port 8787"
Write-Host ""
Write-Host "Terminal 2:"
Write-Host "cd apps\desktop"
Write-Host "npm install"
Write-Host "npm run tauri"
